#!/bin/bash

set -euo pipefail

# https://stackoverflow.com/questions/66053955/how-to-make-sure-my-git-pre-commit-script-wont-get-fooled

# create a temporary directory
tmpdir=$(mktemp -d precommitXXXXXX)

# make sure we clean it up when we're done
trap "rm -rf $tmpdir" EXIT

# check out the index
git checkout-index --prefix=$tmpdir/ -af

# copy mypy cache to speed things up
if [ -d .mypy_cache ]; then
  cp -raf .mypy_cache "$tmpdir/"
fi

# run tests in a subshell so that we end up back in the current
# directory when everything finishes.
(
  source .venv/bin/activate

  cd $tmpdir

  make
)
